# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAbstracta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=1000)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('En pausa', 'En pausa'), ('Cumplida', 'Cumplida'), ('Atrasada', 'Atrasada')], max_length=15)),
                ('prioridad', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_comienzo', models.DateTimeField(verbose_name='comienzo')),
                ('fecha_fin', models.DateTimeField(verbose_name='fin')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('metaabstracta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meta.MetaAbstracta')),
            ],
            bases=('meta.metaabstracta',),
        ),
    ]
