# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_metaabstracta_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaabstracta',
            name='descripcion',
            field=models.CharField(default='Descripcion de meta.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('En pausa', 'En pausa'), ('Cumplida', 'Cumplida'), ('Atrasada', 'Atrasada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='fecha_comienzo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='comienzo'),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vencimiento'),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='prioridad',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=15),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='titulo',
            field=models.CharField(default='TITULO META', max_length=80),
        ),
    ]
