# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_auto_20161024_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaabstracta',
            name='descripcion',
            field=models.CharField(default='Descripcion.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='metaabstracta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('En pausa', 'En pausa'), ('Cumplida', 'Cumplida'), ('Atrasada', 'Atrasada')], default='Pendiente', max_length=15),
        ),
    ]
