# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20161025_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
